### ISSUE TITLE
SELF_URL_PATH is not recognized as environment variable

### ISSUE THREAD

**Issue by jcnoir** [x86dev/docker-ttrss#11]
Hi,
Thank you for this nice docker image.
I use it with the letsencrypt nginx proxy.
With the default configuration I cannot access the web page and I get an error with incorrect SELF_URL_PATH.
I tried to set SELF_URL_PATH as an environment variable but it is not used.
I did workaround by passing these environment variables:
- TTRSS_URL=mysubdomain.mydomain.com
- TTRSS_PROTO=https
Setting the TTRSS_PORT as 443 does not work, I had to omit the value (even if it is 443).

I don't know if it is a bug but it should be at least documented to avoid debugging ...

Thanks.

**Comment by bobberb** [comment]
@x86dev

Another -e issue? I wonder if this is linked to my problem passing
variables.

**Comment by XaF** [comment]
Same problem here!

**Comment by thiesschneider** [comment]
Hey @XaF 
Just use `-e TTRSS_URL=url` and `-e TTRSS_PROTO=https` as @jcnoir did.

**Comment by x86dev** [comment]
Some of the latest commits to TT-RSS contained some changes to SELF_URL_PATH. That was the reason why I extended / fixed the SELF_URL_PATH generation in the startup phase.

For making this to work with e.g. https://github.com/jwilder/nginx-proxy, you also have to use -e VIRTUAL_HOST=<sub.yourdomain.tld>

Just to be sure: You pulled the latest Docker image, right?

**Comment by jcnoir** [comment]
To be sure I just pulled the latest version from the docker hub.
Same results:
- Defining SELF_URL_PATH as env variable  does not work (incorrect SELF_URL_PATH)
- Defining TTRSS_PORT=443 as env variable does not work (incorrect SELF_URL_PATH). You have to omit this variable.

**Comment by x86dev** [comment]
I'll have a look.

**Comment by clx81** [comment]
I have the same problem (incorrect SELF_URL_PATH) !

**Comment by clx81** [comment]
The solution is to set the two env. variables to : TTRSS_SELF_URL  = http://host_ip:port/ and SELF_URL_PATH = http://host_ip:port/ 
Two times the same value. It's work well for me.
When I found a few minutes, I will modify the script : setup-ttrss.sh

**Comment by agampe** [comment]
Note: there's also an issue with TTRSS_PORT that you could also solve. It get's a double colon in lines 81 and 97.

**Comment by TheLux83** [comment]
I just wanted to throw in my 2 cents into this problem. 
I have the same problem. 
Neither -e SELF_URL_PATH=http://rss.domain.com or -e TTRSS_URL=url works for me.

How did you workaround this problem?

**Comment by thiesschneider** [comment]
try to add these ENVs:

      -e SELF_URL_PATH=https://domain.com/ \
      -e TTRSS_SELF_URL=https://domain.com/ \
      -e TTRSS_PROTO=https \
      -e TTRSS_URL=domain.com \

its working for me this way

**Comment by TheLux83** [comment]
Thank you very much @thiesschneider 
This works like a charm :)

**Comment by x86dev** [comment]
Looks like this is solved -- can we close this? Thanks for the help, @thiesschneider.

**Comment by bobberb** [comment]
Please adjust documentation before closing?

**Comment by wicope** [comment]
Hi,  its working for me this way. SSL:
```
        environment:
           TTRSS_WITH_SELFSIGNED_CERT: "1"
           TTRSS_PROTO: "https"
           TTRSS_URL: "192.168.1.124"
#           TTRSS_PORT: "8080"
           TTRSS_SELF_URL: "https://192.168.1.124/"
           SELF_URL_PATH: "https://192.168.1.124/"
           ....
        ports:
            - 443:4443
```
URL to open: https://192.168.1.124/

---

Non SSL:
```
        environment:
#            TTRSS_WITH_SELFSIGNED_CERT: "1"
#            TTRSS_PROTO: "http"
            TTRSS_URL: "192.168.1.124"
            TTRSS_PORT: "8080"
            TTRSS_SELF_URL: "http://192.168.1.124:8080/"
            SELF_URL_PATH: "http://192.168.1.124:8080/"
            ...
        ports:
            - 8080:8080
```
URL to open: http://192.168.1.124:8080/
