### ISSUE TITLE
No connection to database

### ISSUE THREAD

**Issue by reibuehl** [x86dev/docker-ttrss#34]
I have setup the postgres db as a container using the following settings in docker-compose:
```
  ttrssdb:
    container_name: ttrssdb
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
      - PGDATA=/pgdata
    volumes:
      - ./volumes/ttrssdb_pgdata:/pgdata
```
and I use the links directive to connect this container to the ttrss container:
```
  ttrss:
   container_name: ttrss
   build: ttrss/.
   restart: always
   links:
      - ttrssdb:db
   ports:
      - 127:0.0.1:8080:80
   environment:
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=ttrss
   depends_on:
      - ttrssdb
```
but I get errors that the db can't be reached:
```
ttrss          |        TCP/IP connections on port 5432?</pre>[09:15:21/1249] Spawn interval: 120 sec
ttrss          | <pre>Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: Connection refused
ttrss          |        Is the server running on host "localhost" (127.0.0.1) and accepting
ttrss          |        TCP/IP connections on port 5432?
ttrss          | could not connect to server: Address not available
ttrss          |        Is the server running on host "localhost" (::1) and accepting
```
Am I missing an environment variable? Shouldn't the host "db" be used by ttrss instead of "localhost"?
