### ISSUE TITLE
error in ttrss setup: GIt repository does not exist

### ISSUE THREAD

**Issue by bugwelle** [x86dev/docker-ttrss#56]
Hi,

it seems that the git repository configured here: https://github.com/x86dev/docker-ttrss/blob/86744f337415f5c97214c86740e1d668294b305a/root/srv/setup-ttrss.sh#L47
does not exist anymore. Exchanging `git/` with `fox/` (as taken from their website) works. I'm still trying to configure it, though, as I'm currently getting the error  (Update: Ok, my fault; had Postgres accidentally misconfigured)

```
Exception while creating PDO object:SQLSTATE[08006] [7] connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
```

and am debugging it. Just FYI.

Regards,
Andre

Edit:// There seems to be an official docker-compose setup: https://git.tt-rss.org/fox/ttrss-docker-compose.git/

**Comment by bugwelle** [comment]
Also, `ttrss-configure-db.php` is no longer correct. The database schema can now be found at `/sql/psql/schema.sql` instead of `/schema/*.sql`.

**Comment by bugwelle** [comment]
Ok, to summarize the issues:

1. The Git URL of TTRSS has changed
2. They no longer provide `schema/*.sql` -> Postgres emits an error if an empty file is executed
3. They changed something else, etc.

Here is a Git diff to apply to this repository for others to use. I explicitly use a specific commit of TTRSS.
This, of course, is not a proper fix, but it helped my re-start my instance to get backups, etc.

```diff
diff --git a/examples/ttrss_stack.yaml b/examples/ttrss_stack.yaml
index 64393b5..704b215 100644
--- a/examples/ttrss_stack.yaml
+++ b/examples/ttrss_stack.yaml
@@ -24,7 +24,7 @@ services:
       - DB_ENV_USER=postgres
       - DB_HOST=db
       - DB_NAME=ttrss
-      - DB_PASSWORD=XXXXXXXX
+      - DB_PASS=XXXXXXXX
       - DB_PORT=tcp://db:5432
       - DB_PORT_5432_TCP=tcp://db:5432
       - DB_PORT_5432_TCP_ADDR=db
diff --git a/root/srv/setup-ttrss.sh b/root/srv/setup-ttrss.sh
index e98a144..eb5b6a3 100755
--- a/root/srv/setup-ttrss.sh
+++ b/root/srv/setup-ttrss.sh
@@ -44,7 +44,7 @@ setup_nginx()
 setup_ttrss()
 {
     if [ -z "$TTRSS_REPO_URL" ]; then
-        TTRSS_REPO_URL=https://git.tt-rss.org/git/tt-rss.git
+        TTRSS_REPO_URL=https://git.tt-rss.org/fox/tt-rss.git
     fi
 
     if [ -z "$TTRSS_PATH" ]; then
@@ -53,19 +53,16 @@ setup_ttrss()
 
     TTRSS_PATH_THEMES=${TTRSS_PATH}/themes.local
     TTRSS_PATH_PLUGINS=${TTRSS_PATH}/plugins.local
+    TTRSS_GIT_COMMIT=0cb719a40447e30011142714d5e5ce55c051a118
 
     if [ ! -d ${TTRSS_PATH} ]; then
         mkdir -p ${TTRSS_PATH}
-        if [ -n "$TTRSS_GIT_TAG" ]; then
-            echo "Setup: Setting up Tiny Tiny RSS '$TTRSS_GIT_TAG' ..."
-            cd ${TTRSS_PATH}
-            git init .
-            git fetch --depth=1 ${TTRSS_REPO_URL} refs/tags/${TTRSS_GIT_TAG}:refs/tags/${TTRSS_GIT_TAG}
-            git checkout tags/${TTRSS_GIT_TAG}
-        else
-            echo "Setup: Setting up Tiny Tiny RSS (latest revision) ..."
-            git clone --depth=1 ${TTRSS_REPO_URL} ${TTRSS_PATH}
-        fi
+        echo "Setup: Setting up Tiny Tiny RSS; Using commit ${TTRSS_GIT_COMMIT}"
+        git clone ${TTRSS_REPO_URL} ${TTRSS_PATH}
+        old="$(pwd)"
+        cd ${TTRSS_PATH}
+        git checkout "${TTRSS_GIT_COMMIT}"
+        cd "${old}"
 
         mkdir -p ${TTRSS_PATH_PLUGINS}
         git clone --depth=1 https://github.com/sepich/tt-rss-mobilize.git ${TTRSS_PATH_PLUGINS}/mobilize
diff --git a/root/srv/ttrss-configure-db.php b/root/srv/ttrss-configure-db.php
index 062ec1d..a3e7433 100644
--- a/root/srv/ttrss-configure-db.php
+++ b/root/srv/ttrss-configure-db.php
@@ -27,7 +27,7 @@ $config['DB_HOST'] = env($ename . '_PORT_' . $eport . '_TCP_ADDR');
 $config['DB_PORT'] = env($ename . '_PORT_' . $eport . '_TCP_PORT');
 
 // database credentials for this instance
-//   database name (DB_NAME) can be supplied or detaults to "ttrss"
+//   database name (DB_NAME) can be supplied or defaults to "ttrss"
 //   database user (DB_USER) can be supplied or defaults to database name
 //   database pass (DB_PASS) can be supplied or defaults to database user
 $config['DB_NAME'] = env($ename . '_NAME', 'ttrss');
diff --git a/root/srv/update-ttrss.sh b/root/srv/update-ttrss.sh
index c13a3b9..d2a40d0 100755
--- a/root/srv/update-ttrss.sh
+++ b/root/srv/update-ttrss.sh
@@ -11,8 +11,8 @@ update_ttrss()
         return
     fi
 
-    echo "Updating: Tiny Tiny RSS"
-    ( cd ${TTRSS_PATH} && git pull origin HEAD )
+    # echo "Updating: Tiny Tiny RSS"
+    # ( cd ${TTRSS_PATH} && git pull origin HEAD )
 }
 
 update_plugin_mobilize()
```

Example docker-compose.yml:

```yml
version: '2'

services:

  rssreaderdb:
    image: postgres:11
    restart: always
    container_name: rssreaderdb
    expose: 
     - "5432"
    volumes:
     - "./ttrss/db11:/var/lib/postgresql/data"
    environment:
     - "POSTGRES_PASSWORD=docker"
     - "POSTGRES_USER=docker"
     - "POSTGRES_DB=docker"

  rssreader:
    build: ./ttrss/docker-ttrss
    container_name: rssreader
    privileged: true
    depends_on:
     - rssreaderdb
    links:
     - "rssreaderdb:db"
    expose:
     - "8080"
    ports:
     - "8080:8080"
    environment:
     - "SELF_URL_PATH=http://localhost:8080/"

     - "TTRSS_SELF_URL=http://localhost:8080/"
     - "TTRSS_PORT=8080"
     - "TTRSS_PROTO=https"
     - "TTRSS_URL=localhost:8080"

     - "DB_NAME=docker"
     - "DB_USER=docker"
     - "DB_PASS=docker"

     - "DB_PORT=tcp://db:5432"
     - "DB_PORT_5432_TCP=tcp://db:5432"
     - "DB_PORT_5432_TCP_ADDR=db"
     - "DB_PORT_5432_TCP_PORT=5432"
     - "DB_PORT_5432_TCP_PROTO=tcp"
```
(you should use proper password)

Regards,
Andre
